version: "3.9"
services:
   nginx:
     build: ./nginx/
     ports:
       - 80:80
     volumes:
         - ./php_code/:/var/www/html/

   php:
     build: ./php_code/
     expose:
       - 9000
     volumes:
         - ./php_code/:/var/www/html/

   db:    
     build: ./mysql/
     ports:
       - 3306:3306
     volumes: 
        - ./mysql-data/:/var/lib/mysql
     environment:  
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: educaenfam

volumes:
    mysql-data:
