version: "3.9"
services:
  httpd:
    build: ./httpd/
    container_name: httpd
    ports:
      - 80:80
    volumes:
      - ./App/:/var/www/html/
      - ./bootstrap:/usr/local/apache2/htdocs

  mysql:
    build: ./mysql/
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: educaenfam

volumes:
  mysql-data:
  App:
  bootstrap:
